name: report

on:
  schedule:
    - cron: '0 6-18/3 * * *' # Runs every 3 hours between 06:00 and 18:00
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests twilio python-dotenv pydrive

      - name: Create client_secrets.json
        run: |
          echo ${{ secrets.CLIENT_SECRETS_BASE64 }} | base64 --decode > client_secrets.json

      - name: Create mycreds.txt
        run: |
          echo ${{ secrets.MYCREDS_BASE64 }} | base64 --decode > mycreds.txt

      - name: Run the script
        run: python baselinker-to-whatsapp.py
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          X_BLTOKEN: ${{ secrets.X_BLTOKEN }}
          PERSONAL_PHONE_NUMBER: ${{ secrets.PERSONAL_PHONE_NUMBER }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          UPLOAD_URL: ${{ secrets.UPLOAD_URL }}
